### ISSUE TITLE
30V output at the LT1084.

### ISSUE THREAD

**Issue by warlock31415** [dc-power-supply/dc-power-supply#2]
Hey Martin, 
I'd like to point out that you're not going to get 30V at the output of that LT1084 regulator. The MUR420 have a max 1.28V  Vf at 4A. So at full load the voltage at the input of IC2 will sag to 27.7V. This is without accounting for ripple. 

At full load, the simulated ripple is ~1Vpp. Which would mean you will get 26.7V at the input to IC2. The datasheet for the regulator says the typical dropout between input and output is 1.3V.  That makes the output voltage close to 25.5V. Which would leave a 0.5V for the buck converter to play around with. I don't think this is a good safety margin.

I'd suggest going up-to a 120-50V transformer to fix this issue.

/Pratik

PS: Toroid transformers are really expensive ($145 for 50V one on digikey). Would you be willing to maybe design something a little different?

**Comment by lundmar** [comment]
I think you are right on you points - 0.5V is a small margin. I recall to have concluded something similar but I don't remember the details - it's been a while since I last revisited the whole voltage chain.
I'm open to changes and suggestions and if a toroidal is a lot more expensive it would make sense to go with a classic transformer. I made the original design not so much focused on cost but rather on reducing noise.
/Martin
